{
    'name': 'Library Management',
    'version': '18.0.1.0.0',
    'category': 'Tools',
    'summary': 'Library Management System',
    'description': 'A complete library management system with membership management, book tracking, and borrowing controls',
    'author': 'Yazan Alqasem',
    'depends': ['base', 'sale', 'account', 'product', 'sale_product_matrix', 'contacts'],
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/library_book_views.xml',
        'views/library_author_views.xml',
        'views/library_borrowing_views.xml',
        'views/library_membership_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/library_menus.xml',
    ],
    
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}